version: "3.8"

services:
  unittest_db:
    image: "postgres:16"
    platform: linux/amd64
    container_name: unit-test-db
    security_opt:
      - no-new-privileges:true  # Resolve semgrep https://sg.run/0n8q
    environment:
      - POSTGRES_PASSWORD=local_password  # pragma: allowlist secret
    read_only: true  # Resolve semgrep https://sg.run/e4JE
    tmpfs: /var/run/postgresql/
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  data-import:
    build:
      context: ../../../backend
      dockerfile: Dockerfile.data-tools
    platform: linux/amd64
    container_name: pytest-data-import
    environment:
      - ENV=pytest
    command: >
      bash -c "
      python ./data_tools/src/import_static_data/load_db.py &&
      DATA=./data_tools/data/portfolio_data.json5 python ./data_tools/src/import_static_data/import_data.py &&
      DATA=./data_tools/data/funding_partner_data.json5 python ./data_tools/src/import_static_data/import_data.py &&
      DATA=./data_tools/data/funding_source_data.json5 python ./data_tools/src/import_static_data/import_data.py &&
      DATA=./data_tools/data/research_project_data.json5 python ./data_tools/src/import_static_data/import_data.py &&
      DATA=./data_tools/data/user_data.json5 python ./data_tools/src/import_static_data/import_data.py &&
      DATA=./data_tools/data/team_leader_data.json5 python ./data_tools/src/import_static_data/import_data.py &&
      DATA=./data_tools/data/can_data.json5 python ./data_tools/src/import_static_data/import_data.py &&
      DATA=./data_tools/data/agreements_and_blin_data.json5 python ./data_tools/src/import_static_data/import_data.py
      "
    depends_on:
      unittest_db:
        condition: service_healthy
